vich_uploader:
    db_driver: orm

    mappings:
       articles:
          uri_prefix: 'app.path.article_images'
          upload_destination: '%kernel.project_dir%/public%app.path.article_images%'
          namer : Vich\UploaderBundle\Naming\UniqidNamer
       competences:
          uri_prefix: 'app.path.com_images'
          upload_destination: '%kernel.project_dir%/public%app.path.com_images%'
          namer: Vich\UploaderBundle\Naming\UniqidNamer
